
#YuoEnchants enchant is effective Config
[general]
	#enchant is effective
	Repulsion = true
	#enchant is effective
	Slow = true
	#enchant is effective
	DoubleJump = true
	#enchant is effective
	LastStand = true
	#enchant is effective
	LightningDamage = true
	#enchant is effective
	ExpCorrode = true
	#enchant is effective
	Leech = true
	#enchant is effective
	WaterWalk = true
	#enchant is effective
	SuperBlast = true
	#enchant is effective
	FireShield = true
	#enchant is effective
	UnLooting = true
	#enchant is effective
	ManyArrow = true
	#enchant is effective
	RangBreak = true
	#enchant is effective
	StrengthLuck = true
	#enchant is effective
	LavaWalker = true
	#enchant is effective
	FastHeal = true
	#enchant is effective
	Robbery = true
	#enchant is effective
	FireThorns = true
	#enchant is effective
	DiamondDrop = true
	#enchant is effective
	SuperArthropod = true
	#enchant is effective
	DeepFear = true
	#enchant is effective
	BlastArrow = true
	#enchant is effective
	Insight = true
	#enchant is effective
	SuperSmite = true
	#enchant is effective
	WarToWar = true
	#enchant is effective
	Behead = true
	#enchant is effective
	UnDurable = true
	#enchant is effective
	SuperThorns = true
	#enchant is effective
	SuperFall = true
	#enchant is effective
	Melting = true
	#enchant is effective
	Health = true
	#enchant is effective
	SuperFire = true
	#enchant is effective
	HealthToSacrifice = true
	#enchant is effective
	Magnet = true
	#enchant is effective
	SuperProtect = true
	#enchant is effective
	FastBow = true
	#enchant is effective
	BadLuckOfTheSea = true
	#enchant is effective
	SuperArrow = true
	#enchant is effective
	UnLuck = true
	#enchant is effective
	SuperSharp = true
	#enchant is effective
	Thorns = true
	#enchant is effective
	SuperPower = true
	#enchant is effective
	Instability = true
	#enchant is effective
	HandRange = true
	#enchant is effective
	Rebound = true
	#enchant is effective
	Farmer = true
	#enchant is effective
	FireImmune = true

